### PR TITLE
fix: Repo.Diff shouldn't fail given ambiguous branch names

### LINKED ISSUE #195: av stack tree fails when branch name matches filename
`av stack tree` fails in `git diff` when a filename/directory in the root of the repository matches a branch name:

```
❯ av stack tree
develop
<ERROR: cannot get branch info: git diff failed: fatal: ambiguous argument 'copybara': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

### PR DESCRIPTION
**Pull request by travigd**
Fixes #195.

### CODE REVIEW

File: internal/git/diff_test.go [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+
+import (
+	"testing"
+
+	"github.com/aviator-co/av/internal/git"
+	"github.com/aviator-co/av/internal/git/gittest"
+	"github.com/stretchr/testify/require"
+)
+
+func TestRepoDiffAmbiguousPathName(t *testing.T) {
```
Comment (travigd) [inline internal/git/diff_test.go:11]: This test case fails without the change to `Repo.Diff` in this pull request.

**Review by draftcode — APPROVED** [review]
