### PR TITLE
fix: Cleanup on failure for av stack branch-commit

### LINKED ISSUE #102: If a av stack branch-commit command fails, you cannot rerun it
If `av stack branch-commit` command fails because of a pre-commit failure, since the branch is already created, rerunning the command fails.

## Expected
If the command fails, it would be ideal to rollback to the old branch and delete the new branch. That way the command can be replayed after fixing the pre-commit error.

### PR DESCRIPTION
**Pull request by travigd**
Deletes a branch during `av stack branch-commit` if the commit fails (e.g., due to pre-commit hooks).

Also a few minor things like language tweaks and adding `av stack bc` as an alias.

Fixes #102.

### CODE REVIEW

File: cmd/av/stack_branchcommit.go [hunk 1]
```diff
@@ -43,8 +46,9 @@ var stackBranchCommitFlags struct {
 
 var stackBranchCommitCmd = &cobra.Command{
 	Use:          "branch-commit [flags]",
-	Short:        "create a new stacked branch and a commit",
-	Long:         "Create a new branch that is stacked on the current branch, and call git-commit with the specified arguments.",
+	Aliases:      []string{"bc"},
+	Short:        "switch to a new stacked branch commit staged changes to it",
```
Comment (jainankit) [inline cmd/av/stack_branchcommit.go:50]: This is very confusing right now.
```suggestion
	Short:        "create a new stacked branch and commit staged changes to it",
```

**Review by jainankit — APPROVED** [review]
